git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --syntax-theme=gruvbox-dark --line-numbers --side-by-side --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  nerdFontsVersion: "3"
