require("config.lazy")

vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set relativenumber")

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })
vim.cmd.colorscheme('gruvbox-material')
--vim.cmd.colorscheme('catppuccin')
vim.cmd("set number")
require('lualine').setup()
vim.keymap.set('n', '<leader>n', ':Neotree filesystem reveal left<CR>', {})
vim.keymap.set('n', '<leader>c', ':Neotree filesystem close<CR>', {})
vim.keymap.set('n', '<leader>b', ':cclose<CR>', {})
vim.opt.wrap = false
