onboarding = false

[theme]
name = "gruvbox"

[keys]
split_vertical = "prefix+%"
split_horizontal = 'prefix+"'

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "vim-herdr-navigation.left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "vim-herdr-navigation.down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "vim-herdr-navigation.up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "vim-herdr-navigation.right"

[[keys.command]]
key = "prefix+ctrl+y"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "90%"

[ui.toast]
delivery = "system"

[ui.toast.herdr]
position = "bottom-right"

[ui.sound]
enabled = true

